baseURL = "https://oldbig9.github.io/"
title = "OLDBIG9`小仓库"
author = "Whatever"

# 全局配置
summaryLength = 100
hasCJKLanguage = true
defaultContentLanguage = "zh-cn"


[module]
  
  [module.hugoVersion]
    extended = true
    min = "v0.95.0"
  
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
    disable = false


[params]
  colorScheme = "blowfish" # blowfish (default), avocado, fire, ocean, forest, princess, neon, bloody, terminal, marvel, noir, autumn, congo, andslate.
  # defaultBackgroundImage = "/img/background.svg"
  defaultAppearance = "dark"
  enableCodeCopy = true
  enableSearch = true
  highlightCurrentMenuArea = true
  smartTOC = true
  smartTOCHideUnfocusedChildren = true
  dateFormat = "2006年1月2日 15:04:05"

  [params.homepage]
    layout = "profile" #  Valid values are page, profile, hero, card, background
    layoutBackgroundBlur = true
    # homepageImage = "/img/background.svg"
    showRecent = false
    showRecentItems = 3

  [params.list]
    showSummary = true
    constrainItemsWidth = true
    showCards = false
    groupByYear = true
    showHero = true
    heroStyle = "background"

  [params.article]
    showTableOfContents = true
    showHero = true
    heroStyle = "background"
    showReadingTime = false


[menu]

  [[menu.main]]
    identifier = "Docs"
    name = "技术"
    pageRef = "/categories/tech"
    weight = 1

  [[menu.main]]
    identifier = "Songci"
    name = "宋词"
    pageRef = "/songci"
    weight = 2

  [[menu.main]]
    identifier = "Note"
    name = "笔记"
    pageRef = "/note"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    pageRef = "/tags"
    weight = 4

  [[menu.main]]
    identifier = "linqianxi"
    name = "林浅喜"
    url = "https://space.bilibili.com/430967976"
    weight = 10


[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"